-- INSERT INTO order_details (order_id, food_name, quantity)
-- VALUES (1, 'butter chicken', 1),
-- (1, 'fried chicken', 1),
-- (2, 'pasta', 2),
-- (2, 'poutine', 1),
-- (3, 'pizza', 2),
-- (3, 'hamburger', 1),
-- (3, 'ginger ale', 2),
-- (3, 'sprite', 1),
-- (4, 'pizza', 1),
-- (4, 'butter chicken', 1),
-- (4, 'sprite', 1),
-- (4, 'coke', 2);
