DROP TABLE IF EXISTS foods CASCADE;

CREATE TABLE foods (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  in_stock BOOLEAN DEFAULT TRUE,
  picture_url VARCHAR(255) NOT NULL,
  estimated_time INTEGER NOT NULL,
  price INTEGER NOT NULL
);
