DROP TABLE IF EXISTS foods CASCADE;

CREATE TABLE foods (
  id SERIAL NOT NULL,
  name VARCHAR(255) PRIMARY KEY NOT NULL,
  in_stock BOOLEAN DEFAULT TRUE,
  photo VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL
);
