DROP TABLE IF EXISTS food_order CASCADE;

CREATE TABLE food_order (
  id SERIAL PRIMARY KEY NOT NULL,
  food_id INTEGER REFERENCES foods(id) ON DELETE CASCADE,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE
);
